"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../css/style.css";
import { ContextProvider } from "../contexts/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={inter.className}>
          {children}
        </body>
      </ContextProvider>
    </html>
  );
}